### ISSUE TITLE
Getting the relation values via the sdk

### ISSUE THREAD

**Issue by falko100** [directus/sdk#109]
I'm trying to get the `filename_download` value from relation.
Yet when I use the follow code all I get for the `image` field is the id (uuid).
Works fine via graphql, but implementing that into my simple app is rather complex.

```ts
const drinks = await directus.items<string, Drink>('drinks')
  .readByQuery({
    limit: -1,
    deep: {
      image: {
        _limit: 1,
      }
    },
  });
```

Anyone know how to get the relations via the sdk?

**Comment by rijkvanzanten** [comment]
What you're looking for is the `fields` parameter, not the `deep` parameter 👍🏻 https://docs.directus.io/reference/query.html#fields

In this case, it'd be:

```js
const drinks = await directus.items<string, Drink>('drinks')
  .readByQuery({
    limit: -1,
    fields: ['*', image.filename_download'],
  });
```

(the first `*` is to get all top-level fields. If you really wanna get just the filename_download, you can omit that). Groetjes!
