### ISSUE TITLE
Creating a user with SDK returns `undefined`

### ISSUE THREAD

**Issue by adanielyan** [directus/sdk#114]
When I create user with `directus.users.createOne()` the user is created, however this function returns `undefined` instead of a User object.

**Comment by paescuj** [comment]
The role which you use to create the user must have read access on the `directus_users` collection in order to retrieve the newly created user on `directus.users.createOne()`.

**Comment by adanielyan** [comment]
Ah, of course, that makes sense, although not very intuitive. Would be great if that was mentioned in docs. 

In this case how do I know if the user was created successfully? Should I assume that if createOne didn't throw then the user was created?
