### ISSUE TITLE
Type declarations failed to resolve

### ISSUE THREAD

**Issue by AnmSaiful** [directus/sdk#154]
**Directus SDK Version:** `10.3.4`
**TypeScript Version:** `4.5.2`
**NodeJS Version:** `16.20.1`

```ts
import { Directus } from “@directus/sdk”;
```

The above line yields the following error:

> Cannot find module `@directus/sdk` or its corresponding type declarations.

While exploring the `package.json`, I found the type declaration file is mapped to `dist/index.d.ts`

However, there is no such file but `dist/types/index.d.ts`

As a workaround, I created a custom declaration file, `@directus/sdk.d.ts`, with the following line that helped resolve the type declarations correctly.

But since there are some errors in the SDK’s type declaration, this prevents successful linting.

For example, running `tsc --noEmit` emits a couple of errors, including the following:

```bash
node_modules/@directus/sdk/dist/types/items.d.ts:57:188 - error TS1005: ‘:’ expected.

57 type ArrayTreeBranch<U, Path extends string, Val = Record<string, never>, NU extends Record<string, any> = NonNullable<U>> = Extract<NU, Record<string, unknown>> extends infer OB extends Record<string, any> ? Val extends (infer _)[] ? DeepPathToObject<Path, OB, Val[number]> : DeepPathToObject<Path, OB, Val> : Val extends (infer _)[] ? DeepPathToObject<Path, NU, Val[number]> : DeepPathToObject<Path, NU, Val>;
```

Can you offer a **workaround** that can suppress the error of the type declaration and lining?

Thanks in advance.

**Comment by rijkvanzanten** [comment]
Make sure to update to 10.3.5, that should've fixed the issue 👍🏻  Happy to reopen if that didn't do the trick

**Comment by AnmSaiful** [comment]
Thank you so much for the update, @rijkvanzanten . This is called luck! I updated the SDK 4 days ago, and there was a release with the fix three days ago.

With the update, the type declaration error is gone, but it raised some new errors, including the missing `PartialItem` type from the `@directus/sdk` import, and it seems there's a big change brought to the `query` parameter that breaks the type checking.

The error says:

> Types of property `fields` are incompatible.

And I also see the declaration matches the above statement:

```ts
declare type QueryMany<T> = QueryOne<T> & {
    sort?: Sort<T>;
    limit?: number;
    offset?: number;
    page?: number;
    meta?: keyof ItemMetadata | '*';
    groupBy?: string | string[];
    aggregate?: Aggregate;
    alias?: Record<string, string>;
};
```

But the compiled code works without any issues. That said, there's a mismatch between the declaration and implementation.

Can you please check and let me know if I'm missing anything?

Thanks in advance.

**Comment by rijkvanzanten** [comment]
I'm not sure about that. I'm not too familiar with the SDK or it's internal workings. We're currently focussed on the new SDK (see #new-sdk on [Discord](https://directus.chat), and https://docs.directus.io/guides/sdk/getting-started.html) in which a lot of those weirdnesses are solved on a foundational level 🙂

**Comment by AnmSaiful** [comment]
Okay, it's better to apply quick and dirty methods to eliminate the errors and wait until the beta SDK becomes stable. Thanks for the update.
