### ISSUE TITLE
Retreiving users_me with the Beta SDK and GraphQL

### ISSUE THREAD

**Issue by vinyll** [directus/sdk#159]
Once logged in, the following call works just fine:

`POST /graphql/system`

```gql
query me {
    users_me {
        id
    }
}
```

However using the SDK the URL does not refer to the `/graphql/system` url but to `/graphql`:

```js
const client = createDirectus('https://example.com')
  .with(graphql())
  .with(authentication())
```

Then how to force using the `/graphql/system` url for system calls?

**Comment by rijkvanzanten** [comment]
Docs and examples for the new SDK are currently in-works. The typedoc is already up https://docs.directus.io/packages/@directus/SDK%20(beta)/module.graphql/interfaces/interface.GraphqlClient.html

The SDK source code is right here: https://github.com/directus/directus/pull/18987. Once v11 is released, it's part of the monorepo
