### ISSUE TITLE
Call endpoints extension

### ISSUE THREAD

**Issue by emrahcetiner** [directus/sdk#31]
Is there a way for calling custom endpoints with SDK?

**Comment by azrikahar** [comment]
There is! You can call any URL, including custom endpoints, via [the transport object](https://docs.directus.io/reference/sdk/#transport), which uses [axios](https://github.com/axios/axios) by default. 👍

Examples of calling a custom endpoint using the transport should look like:

```js
// GET
directus.transport.get('http://example.com');

// POST
directus.transport.post('http://example.com', data);
```

There's also `patch`, `put`, `delete`, `head`, and `options`. Additional reference via source code:

https://github.com/directus/sdk/blob/523e067a3f3cf61c531e2bc52aa8a46230bcb102/src/transport.ts#L34-L58

**Comment by emrahcetiner** [comment]
@azrikahar thanks for the help. I have one more question. Why should I use transport instead of axios directly? What are the advantages?

**Comment by azrikahar** [comment]
Apart from reusing the same axios instance with the transport, it contains the access token in it's header, and a little custom beforeRequest to refresh access token to prevent expiration:

https://github.com/directus/sdk/blob/523e067a3f3cf61c531e2bc52aa8a46230bcb102/src/base/directus.ts#L92-L107

there isn't really other advantages (that I know of) since it's a thin wrapper around axios at the end of the day. 👍

**Comment by eikaramba** [comment]
thank you very much. i actually implemented this myself by adding an endpoint method to the directus object
```
const directus = new Directus(import.meta.env.VITE_APIURL,{auth:{mode:"json"}});

async function request(path,method,data){
    const options = {
        method: method,
        headers: {
            "Accept": "application/json",
            "Authorization": `Bearer ${await directus.auth.token}`
        }
    };
    if(method==="POST" || method==="PATCH"){
        options.body = JSON.stringify(data);
        options.headers['Content-Type'] = "application/json";
    }
     //request endpoint name via fetch
     let request = await fetch(`${import.meta.env.VITE_APIURL}/${path}`,options);
     if (request.status == 401) { //If token is expired try to refresh it and send request again
        const content = await request.json();
        if(content.errors && content.errors[0].message.indexOf("Token expired")!= -1){
            await directus.auth.refresh();
            options.headers['Authorization'] = `Bearer ${await directus.auth.token}`;
            request = await fetch(`${import.meta.env.VITE_APIURL}/${path}`,options);
        }
     }
     if (request.status == 204) {
        //no content
        return;
      } else if (request.headers.get("content-type").indexOf("application/json") > -1) {
        return await request.json();
      } else {
        return await request.text();
      }
}
directus.endpoints = (path)=>{
    return {
        get: async ()=>request(path,"GET",null),
        post: async (data)=>request(path,"POST",data),
        patch: async (data)=>request(path,"PATCH",data),
        delete: async ()=>request(path,"DELETE",null),
    }
}

export default directus;
```

but now i see i can delete that code!
