### ISSUE TITLE
Can not create items via the JS-SKD

### ISSUE THREAD

**Issue by marco910** [directus/sdk#41]
### Describe the Bug

I'm trying to create one or many items by using the JS-SDK of Directus. Every time I'm calling `createOne` I don't retrieve the new created item but all others of the collection and the new item does not get create. The same happens when using `createMany`.

When using `updateOne` to update a single item, everything works fine.

### To Reproduce

1. Create new `Direcuts` instance
2. Use static auth token
3. Use `directus.item()` to select a collection
4. Try to create a new item by using `createOne` or `createMany`

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.14.2

### What database are you using?

MySQL 8

### What browser are you using?

Firefox

### How are you deploying Directus?

Ubuntu server using PM2

**Comment by rijkvanzanten** [comment]
Can you share the full code snippet you're using? Thanks 🙂

**Comment by marco910** [comment]
@rijkvanzanten Sure!

```
const directus = new Directus("directus_url_here");
  await directus.auth.static("api_token_here");
  const inserate = directus.items("inserate");

  // Perform action
  try {
    inserate.createOne({
        ...data,
      })
      .then((res) => console.log(res));
  } catch (err) {
    console.log("error creating inserat", err);
  }
```

`inserate` is the name of the collection where I want to add the item to.

**Comment by marco910** [comment]
After testing a bit around, I noticed that there was a server-side error on the Directus server. This was caused because I've tried to pass an empty string as a value for an integer field which doesn't work. After switching this to `null` everything works fine.

@rijkvanzanten Thanks for your fast response!
