### ISSUE TITLE
[Types] imprecise type for fields in readByQuery

### ISSUE THREAD

**Issue by ganlhi** [directus/sdk#46]
The current typing for `fields` in the following code is always resolved as `string | string[] | undefined`: 
```
declare type QueryOne<T = unknown> = {
    fields?: T extends unknown ? string | string[] : DotSeparated<T, 5> | DotSeparated<T, 5>[];
    search?: string;
    deep?: Deep<T>;
    export?: 'json' | 'csv' | 'xml';
    filter?: Filter<T>;
};
```

As far as I know it is because `T`, describing a collection item, so a record, always extends `unknown`.

**Comment by rijkvanzanten** [comment]
How are you calling Directus on the top level? I believe it's supposed to pass T down from the main Schema object you pass in, for example:

```ts
type BlogPost = {
	id: ID;
	title: string;
};

type BlogSettings = {
	display_promotions: boolean;
};

type MyCollections = {
	posts: BlogPost;
	settings: BlogSettings;
};

// This is how you feed custom type information to Directus.
const directus = new Directus<MyCollections>('http://url');
```

**Comment by rijkvanzanten** [comment]
@jonahgoldwastaken You might have more insights on this topic though, as this was touched in https://github.com/directus/sdk/pull/22 if I'm not mistaken 🙂

**Comment by ganlhi** [comment]
Indeed I call Directus with a custom type map for the collections, and the type of the collection I want to query is the record type I was referring to.

**Comment by rijkvanzanten** [comment]
> Indeed I call Directus with a custom type map for the collections, and the type of the collection I want to query is the record type I was referring to. 

Can you share a minimal reproduction to debug with that's behaving incorrectly?

**Comment by jonahgoldwastaken** [comment]
Yeah sorry about that! I made a small mistake that's correctly called out by @ganlhi. The ternary should test `unknown extends T` instead of `T extends unknown`. I'll open a PR to fix this in a little bit

**Comment by SaizFerri** [comment]
@jonahgoldwastaken @rijkvanzanten This is broken for me on latest version. When trying to request deeper levels like `logo.*` typescript complains.

Issue seems to be on the definition of `DotSeparated` but can't figure it out. This was working on `v10.1.4`.

```typescript
export interface DirectusFile {
  id: string;
  filename_download: string;
  width?: number;
  height?: number;
  type: string;
  title: string;
}
export interface DirectusImage extends DirectusFile {
  id: string;
  filename_download: string;
  width: number;
  height: number;
  type: string;
  title: string;
}
export interface BaseCollection {
  sort: Nullable<number>;
  status: Status;
  user_created: string;
  date_created: string;
  user_updated: string;
  date_updated: string;
}
export interface Partner extends BaseCollection {
  id: number;
  name: string;
  website: string;
  logo: DirectusImage;
}

export type Collections = {
  partners: Partner;
};

const directus = new Directus<Collections>(
  process.env.NEXT_PUBLIC_DIRECTUS_URL as string
);

export async function getPartners() {
  return await directus.items(Collection.PARTNERS).readByQuery({
    limit: -1,
    fields: ["*", "logo.*"], // ERROR: Type '"logo.*"' is not assignable to type '"*" | "sort" | "id" | "name" | "website" | "status" | "user_created" | "date_created" | "user_updated" | "date_updated" | "logo"'. Did you mean '"logo"'?
    filter: {
      status: {
        _in: COLLECTION_STATUS,
      },
    },
  });
}
```

**Comment by Vincent-HD** [comment]
Same problem as @SaizFerri in `@directus/sdk: 10.3.3`

```Typescript
DirectusInstance.items('sub_family').readByQuery({
    fields: ['*', 'family_id.*'] // ERROR: Type '"family_id.*"' is not assignable to type '"id" | "code" | "family_id" | "is_deleted" | "is_visible" | "order" | "title" | "*"'. Did you mean '"family_id"'?
});
```

**Comment by rijkvanzanten** [comment]
@Vincent-HD please open a new issue 👍🏻
