### ISSUE TITLE
Issue when directus is mounted on a sub-folder

### ISSUE THREAD

**Issue by avionbg** [directus/sdk#51]
When app is mounted on a sub-folder trough nginx proxy configuration, 
client code fails to authenticate properly.

More details of the setup can be found here [directus bug report](https://github.com/directus/directus/discussions/4480#discussioncomment-3578333).

I suspect the culprit is here (somewhere around line 821 in node_modules/@directus/sdk/dist/sdk.bundler.js):

```js
this._transport.post('/auth/login'
```

Now how to fix this or take the sub-folder in consideration I'm not sure but there should be some kind of additional configuration that would allow users to pinpoint the calls to exact path.

**Comment by licitdev** [comment]
@avionbg Upon a closer inspection, it looks to be possible to instantiate the Directus SDK instance with the subfolder in the URL.
```ts
const directus = new Directus('http://directus.example.com/subfolder');
```
Kindly confirm if the above works. Thanks!

**Comment by rijkvanzanten** [comment]
Linear: [ENG-71](https://linear.app/directus/issue/ENG-71/issue-when-directus-is-mounted-on-a-sub-folder)
