### ISSUE TITLE
deep no longer works?

### ISSUE THREAD

**Issue by lessborders** [directus/sdk#55]
Why does

```
deep: {
    categories: {
      _limit: -1,
    },
 }
```

 return
    
`&deep=%7B"categories":%7B"_limit":-1%7D%7D`

**Comment by br41nslug** [comment]
This decodes to `&deep={"categories":{"_limit":-1}}` so that should be fine. do you have an actual error when doing this query?

**Comment by lessborders** [comment]
Oh maybe I'm wrong, it's just retrieving no data when in theory it should
be. (Maybe we can get some docs on readByQuery?

**Comment by br41nslug** [comment]
The docs are not exhaustive i know but for reference `readByQuery` uses the same options as the API (as it mostly just passes it along to the API). So this should work as a reference for `readByQuery` https://docs.directus.io/reference/query.html

**Comment by rijkvanzanten** [comment]
Seems like this is usage confusion rather than a bug in the SDK. Closing for now 👍🏻

**Comment by reqwire** [comment]
Although this is closed, I still can't get deep to ever work. :/
