### ISSUE TITLE
`OneItem` makes all properties optional

### ISSUE THREAD

**Issue by fehnomenal** [directus/sdk#70]
I have a type `workshops` (generated with code from https://github.com/directus/directus/pull/8531 and custom modifications):
```ts
export type workshops = {
  // more unrelated fields...
  name?: string;
  status: string;
  uuid: string;
  workshop_image?: string | directus_files;
};
```

When accessing them with the sdk:
```ts
    const workshops = await directus.items('workshops').readByQuery({
      fields: [
        'uuid',
        'status',
        'name',
        'workshop_image.id',
        'workshop_image.width',
        'workshop_image.height',
      ],
      limit: 6,
      sort: ['name'],
    });
```
each workshop looks like this:

![image](https://user-images.githubusercontent.com/9959940/194870542-0d3ea981-e567-4bf0-99bf-a0905ebc8b2d.png)

I would expect for the optionality to be carried over from the types. I want only `name` and `workshop_image` to be optional, the other two fields required.

It does not matter if I select `fields` or not which means both `PartialItem` and `PickedPartialItem` suffer the same flaw.

Pinging @jonahgoldwastaken as you seem to be the master of types :joy:

**Comment by jonahgoldwastaken** [comment]
Yeah I discussed this with @rijkvanzanten a couple of weeks ago as someone else pointed out this problem but no action has been taken yet. I'll look into this in a bit
