### ISSUE TITLE
beforeRequest override doesn't work as expected

### ISSUE THREAD

**Issue by drico** [directus/sdk#79]
While trying to allow self-signed certificate, I intended to change axios configuration.
For that, I started overriding the axios config with the following pattern :
```
new Directus<CustomTypes>("http://localhost:8055", {
    transport: {
      url: "http://localhost:8055",
      beforeRequest: async (config) => {
        return config;
      },
    },
  });
```

But I've got 2 problems : 
First small problem is that, in my opinion, url should not be required (it should default to the url provided in constructor).

Second big problem is that when doing this (ie setting beforeRequest), all the Authorization headers vanish eventhough I didn't change the config yet.
I was able to check this issue by adding a `console.log(config);` just after the `config = await this.beforeRequest(config);` line in [sdk/src/base/transport.ts](https://github.com/directus/sdk/blob/e7d5cfec18ab6236293c9471996ec0bd539fc3d1/src/base/transport.ts) :

When setting `beforeRequest`, `config.headers` is not set, while it is set when `beforeRequest` is not set.

@directus/sdk : v10.1.4

**Comment by br41nslug** [comment]
You'll need to implement this logic if you're overwriting teh `beforeRequest` function but want to keep built-in functionality https://github.com/directus/sdk/blob/e7d5cfec18ab6236293c9471996ec0bd539fc3d1/src/base/directus.ts#L92
