### ISSUE TITLE
build error: Type 'T' is not assignable to type...

### ISSUE THREAD

**Issue by 5m1Ly** [directus/sdk#84]
### Desc
Uppon building the sdk there is an error being thrown which stops the building process. The build error was created when the last commit ([dd76016](https://github.com/directus/sdk/commit/dd76016d597a5209084898b5fbc234603059cafd)) has been published.

### Thrown Error
```
[!] (plugin rpt2) Error: path:/sdk/src/handlers/fields.ts(29,4): semantic error TS2322: Type 'T[]' is not assignable to type '(NonNullable<DefaultItem<T>> | NonNullable<PickedDefaultItem<T, any, Record<string, unknown>>>)[]'.
  Type 'T' is not assignable to type 'NonNullable<DefaultItem<T>> | NonNullable<PickedDefaultItem<T, any, Record<string, unknown>>>'.
```

### Fix
Within this pull request [pull#81](https://github.com/directus/sdk/pull/81) at commit [30fd0c6](https://github.com/directus/sdk/pull/81/commits/30fd0c6134b09e203fd70b2170d67845224a82d4) the issue has been resolved by @VerantoWander.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/sdk/pull/89
