### ISSUE TITLE
"Too much recursion" error when setting storage prefix

### ISSUE THREAD

**Issue by Blechlawine** [directus/sdk#88]
When I set a storage prefix for the directus sdk like this:
```javascript
const _directus = new Directus("http://localhost:8055", {
    storage: {
        prefix: "something-",
    },
});
```
Docs to this prefix here: https://docs.directus.io/reference/sdk.html#reference

I get the error: "too much recursion" in Firefox, when it tries to refresh the auth token. If I remove the saved auth_token and the accompanying expiry stuff from localstorage, it works again until the next refresh.
It also works, if I don't set a storage prefix in the directus options.
I found this issue: #53 which was about a similar sounding problem and a similar cause, with which I narrowed my problem down to the storage prefix.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-69](https://linear.app/directus/issue/ENG-69/too-much-recursion-error-when-setting-storage-prefix)
